{
 "title": "Мониторинг логов приложения",
 "tags": [
  "logs",
  "monitoring"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Последние логи приложения",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"logs-app\"}"
    }
   ]
  },
  {
   "title": "Критические ошибки",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"logs-app\"} |= \"CRITICAL\" [1m]) > 0"
    }
   ]
  },
  {
   "title": "Количество логов по уровням",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({job=\"logs-app\"} [$__interval]))"
    }
   ]
  }
 ]
}